version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.3
    steps:
      - checkout
      - run:
          name: install
          command: |
            mkdir -p ~/venv
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            pip install --upgrade pip
            pip install pytest
            pip install flake8
      - run:
          name: run test
          command: |
            . ~/venv/bin/activate
            flake8 --statistics
            pytest --junitxml=test-results/junit.xml
      - store-test-results:
          path: test-reports
      - store_artifacts:
          path: test-reports
          destination: test-reports