version: 2
jobs:
  build:
    docker:
      - image: circleci/python3.7
    working_directory: ~/devops
    steps:
      - checkout
      - run:
          name: dependencies
          command: |
            python3 -m venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install pytest
            pip install flake8
      - run:
          name: run test
          command: |
            . venv/bin/activate
            flake8 --exclude-env* --statistics
            pytest --junixml-test-results/junit.xml
      - store-test-results:
          path: test-reports
      - store_artifacts:
          path: test-reports
          destination: test-reports